In [2]:
import torch
import numpy as np
import os 

In [3]:
path = "D:\\Vikas\\lie_detection\\BrainWaves\\data\\wvu\\wvu\\"

sub_directories = list(os.listdir(path))
sub_directories

['data02', 'data03']

In [4]:
import pandas as pd

columns = ["path", "label"]
df = pd.DataFrame(columns = columns)

ans = []

In [5]:
data_dest = "d:/Vikas/lie_detection/BrainWaves/data/preprocessed/"
# os.chdir("d:/Vikas/lie_detection/BrainWaves")
print(os.path.exists(data_dest))
print(os.getcwd())
print(list(os.listdir(os.getcwd())))


total_count = {}
total_outliers = {}
for data_dir in sub_directories:
    

    # count_j, it is the file counter for the npz files 
    count_j = 1
    for j in os.listdir(path + data_dir):
        data = np.load(path + data_dir + "\\" + j, allow_pickle= 1)
        # print(list(data.keys()))

        eeg_raw = data["eeg_raw"]
        label = data["annotations"]
        eeg_filt = data["eeg_filt"]

        # print(eeg_filt.shape, '----------', len(eeg_filt))
        x_path = os.path.join(data_dest,data_dir)
         
        if not os.path.exists(x_path):
            os.mkdir(x_path)
       
        count = 1
        outliers = 0
        for indx, val in enumerate(eeg_filt):
            if label[indx] == 0 or label[indx] == 1:
                pass
            else:
                outliers += 1
                continue

            
            # np.save(f'{data_dest}/{data_dir}/{data_dir}_{count_j}_{count}',eeg_filt[indx])
            # Append Dict as row to DataFrame
            new_row = {"path": f'{data_dest}/{data_dir}/{data_dir}_{count_j}_{count}', "label" : label[indx]}
            ans.append(new_row)
            count += 1
      
        # print(count, outliers, "count, outliers")
        # count - 1, because we are incrementing count at the end of the above loop
        total_outliers[f'{data_dir}_{count_j}_{count - 1}'] = outliers
        total_count[f'{data_dir}_{count_j}_{count - 1}'] = count - 1
        count_j += 1
        


True
d:\Vikas\lie_detection\BrainWaves
['data', 'data-preprocess.ipynb', 'dataset.py', 'demo.py', 'documentation.txt', 'independent_subject_test.csv', 'jupy.ipynb', 'labels_all_data.csv', 'labels_smote', 'labels_smote.csv', 'model.py', 'New Text Document.txt', 'results', 's250-1000-smote.npy', 's250-1000-smote_until_9444.npy', 'subject_dependent_train_val.csv', 'test.csv', 'test.py', 'train.py', 'train_val.csv', 'Untitled-1.ipynb', 'utils.py', '__pycache__']


In [9]:
print(sum(total_outliers.values()))
print(sum(total_count.values()))

print(sum(total_outliers.values()) + sum(total_count.values()))



4546
12019
16565


In [10]:
df = pd.DataFrame(ans)

In [7]:
total_outliers

{'data02_1_3': 75,
 'data02_2_0': 80,
 'data02_3_0': 62,
 'data02_4_46': 26,
 'data02_5_0': 65,
 'data02_6_40': 13,
 'data02_7_22': 42,
 'data02_8_52': 12,
 'data02_9_49': 21,
 'data02_10_17': 49,
 'data02_11_51': 19,
 'data02_12_29': 43,
 'data02_13_31': 41,
 'data02_14_33': 33,
 'data02_15_6': 61,
 'data02_16_32': 36,
 'data02_17_30': 35,
 'data02_18_29': 52,
 'data02_19_25': 43,
 'data02_20_24': 37,
 'data02_21_25': 44,
 'data02_22_19': 36,
 'data02_23_19': 37,
 'data02_24_23': 33,
 'data02_25_26': 38,
 'data02_26_17': 40,
 'data02_27_80': 2,
 'data02_28_53': 14,
 'data02_29_63': 11,
 'data02_30_64': 11,
 'data02_31_58': 2,
 'data02_32_44': 23,
 'data02_33_28': 31,
 'data02_34_46': 26,
 'data02_35_41': 35,
 'data02_36_51': 14,
 'data02_37_37': 30,
 'data02_38_41': 20,
 'data02_39_59': 26,
 'data02_40_21': 62,
 'data02_41_60': 20,
 'data02_42_58': 6,
 'data02_43_57': 1,
 'data02_44_74': 4,
 'data02_45_72': 1,
 'data02_46_58': 2,
 'data02_47_59': 3,
 'data02_48_60': 12,
 'data02_49_40

In [15]:
df.to_csv("labels.csv")

In [74]:
eeg_raw.shape

(81, 8, 1800)

In [22]:
for i in eeg_raw:
    if i.shape != (8, 1800):
        break

In [59]:
eeg_raw[1].shape

(8, 1800)

In [25]:
for i in label:
    print(i)

0
0
0
0
0
0
0
1
0
0
0
0
1
3
3
3
0
0
0
0
0
1
1
1
0
0
0
0
1
0
0
3
0
3
3
0
1
0
0
0
1
0
0
1
0
0
0
0
0
0
0
1
1
0
0
0
0
1
0
0
0
0
0
0
1
0
0
0
0
0
0
1
1
0
0
0
0
0
3
1
0


In [26]:
import numpy as np

# Example array
arr = np.array([
    [1, 2, 3],
    [4, 0, 6],
    [7, 8, 9],
    [1, 5, 0]
])

# Determine which rows contain at least one 0 or 1
mask = np.any(np.isin(arr, [0, 1]), axis=1)

# Apply the mask to filter rows
filtered_arr = arr[mask]

print("Original Array:")
print(arr)
print("\nFiltered Array:")
print(filtered_arr)


Original Array:
[[1 2 3]
 [4 0 6]
 [7 8 9]
 [1 5 0]]

Filtered Array:
[[1 2 3]
 [4 0 6]
 [1 5 0]]


In [30]:
eeg_raw.shape

(81, 8, 1800)

In [17]:
f = np.load("D:/Vikas/lie_detection/BrainWaves/data/preprocessed/data02/data02_1_1.npy", allow_pickle=1)

In [18]:
f

array([[-0.20047627384514566, -0.2278284692323248, -0.25803387600418576,
        ..., -8.080546685062371, -7.922294192244261, -7.76485777683833],
       [-14.712831118568207, -14.830403455249662, -14.948973235054844,
        ..., -7.405707336209724, -7.258721284881276, -7.112575131961276],
       [-11.380414392710742, -11.535425284430408, -11.688172094699976,
        ..., 1.3188840298663629, 1.3030015683128544, 1.2869253063584636],
       ...,
       [2.721739194830571, 2.5714381383863985, 2.421237150696417, ...,
        1.8264446041052078, 1.8093002738747068, 1.7916427711400233],
       [2.0113721821043455, 1.9028222765416982, 1.7940726707067274, ...,
        1.924533134046098, 1.9061526954773864, 1.887244201387385],
       [1.8524434856052838, 1.7491403036788822, 1.6456153830103046, ...,
        2.2972744895254573, 2.273203844415414, 2.24857565505847]],
      dtype=object)

In [19]:
import numpy as np

In [20]:
np.arange(1,32)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [ ]:
[i for i in range(1, 33)]